version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1
  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  build:
    working_directory: ~/ng-project
    docker:
      - image: cimg/node:16.19.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          command: npm install
          name: Install Dependencies
      - save_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          command: npm run test
          name: Run Unit Tests
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
